#pragma once

#define SCREEN_WIDTH 640
#define SCREEN_HEIGHT 480
#define LEFT 0
#define RIGHT 1
#define DEFAULT_GAME_SPEED 600
#define GAME_SPEED_CHANGE 150
#define SECONDS_BETWEEN_REFRESH 0.5
#define BMPS_OFFSET_FROM_DISTANCE (int)timeManager.distance % 478 + 0.5
#define LEFT_LANE_POSITION SCREEN_WIDTH / 2 - 85
#define RIGHT_LANE_POSITION SCREEN_WIDTH / 2 + 65
#define LEFT_TREES_POSITION SCREEN_WIDTH / 2 - 270
#define RIGHT_TREES_POSITION SCREEN_WIDTH / 2 + 270
#define SCORE_INCREASE_RATE 50
#define X 0
#define Y 1
#define PLAYER_DEFAULT_POSITION_X SCREEN_WIDTH / 2 + 30
#define PLAYER_DEFAULT_POSITION_Y SCREEN_HEIGHT / 2 + 120
#define PLAYER_POSITION_CHANGE_RATIO 3
#define ENEMY_POSITION_CHANGE_RATIO_X 1
#define ENEMY2_POSITION_CHANGE_RATIO_X 3
#define ENEMY_POSITION_CHANGE_RATIO_Y (2 + timeManager->worldTime * 0.01)
#define ENEMY2_POSITION_CHANGE_RATIO_Y (1 + timeManager->worldTime * 0.01)
#define NPC_POSITION_CHANGE_RATIO_Y (2 + timeManager->worldTime * 0.01)
#define ROAD_BORDER_RIGHT SCREEN_WIDTH - 200
#define ROAD_BORDER_LEFT 175
#define SCREEN_BORDER_RIGHT SCREEN_WIDTH - 25
#define SCREEN_BORDER_LEFT 25
#define MAX_HP 5
#define ENEMY_SHOOT 1
#define ENEMY_FORCE_OUT 0
#define HP_INCREASE_SCORE_THRESHOLD 5000
#define IMMORTALITY_TIME 5
#define SCORE_RESTRICTION_TIME 5
#define LANE_0_POSITION SCREEN_WIDTH / 2 + 30
#define LANE_1_POSITION SCREEN_WIDTH / 2 - 30
#define LANE_2_POSITION SCREEN_WIDTH / 2 + 100
#define LANE_3_POSITION SCREEN_WIDTH / 2 - 80
#define SCORES_ON_PAGE 6
#define BULLET 0
#define ROCKET 1
#define LASER 2
#define WEAPON_POSITION_CHANGE_RATE 20
#define VELOCITY_BULLET 100
#define VELOCITY_ROCKET 200
#define VELOCITY_LASER 50
#define POWER_UP_POSITION_CHANGE_RATE 2
#define SHOOT_SCORE_INCREASE_RATE 100
#define SECONDS_TO_MILISECONDS 0.001
#define SECOND 1000
#define POINTS_MULTIPLICITY 50
#define INPUT_DELAY 100
#define SCREEN_PLAYER_BORDER_BOTTOM SCREEN_HEIGHT - 90
#define SCREEN_BORDER_BOTTOM SCREEN_HEIGHT + 150
#define SCREEN_BORDER_TOP 120
#define CAR_SPAWN_BOTTOM SCREEN_BORDER_BOTTOM
#define LASER_OFFSET 100
#define WEAPON_OFFSET 50
#define VERTICAL_COLLISION_OFFSET 45
#define HORIZONTAL_COLLISION_OFFSET 25
#define POWER_UP_APPEARANCE_CHANCE 0.25
#define POWER_UP_APPEARANCE_RAND 100
#define POWER_UP_APPEARANCE_CONDITION POWER_UP_APPEARANCE_RAND * POWER_UP_APPEARANCE_CHANCE
#define LANE_CHOICE_RAND 4
#define POWER_UP_TYPE_CHANCE 0.5
#define POWER_UP_TYPE_RAND 10
#define POWER_UP_TYPE_CONDITION POWER_UP_TYPE_RAND * POWER_UP_TYPE_CHANCE
#define CONTROLS_LEGEND_HEIGHT 72
#define FUNCTIONALITIES_POSITION_X SCREEN_WIDTH - 182
#define FUNCTIONALITIES_POSITION_Y SCREEN_HEIGHT - 40
#define FUNCTIONALITIES_WIDTH 182
#define FUNCTIONALITIES_HEIGHT 40
#define TEXT_ALLIGN_CENTER screen->w / 2 - strlen(text) * 8 / 2
#define TITLE_POSITION_Y 7
#define TEXT_ALLIGN_CENTER_FUNCTIONALITIES TEXT_ALLIGN_CENTER + 226
#define FUNCTIONALITIES_TITLE_POSITION_Y SCREEN_HEIGHT - 36
#define FUNCTIONALITIES_1_POSITION_Y SCREEN_HEIGHT - 25
#define FUNCTIONALITIES_2_POSITION_Y SCREEN_HEIGHT - 15
#define HEART_POSITION_X SCREEN_WIDTH / 2 + 200 + 20 * i
#define HEART_POSITION_Y 20
#define LEGEND_1_POSITION_Y 23
#define LEGEND_2_POSITION_Y 39
#define LEGEND_3_POSITION_Y 55
#define POP_UP_POSITION_Y SCREEN_HEIGHT / 2
#define POP_UP_HEIGHT 35
#define POP_UP_TEXT_POSITION_Y SCREEN_HEIGHT / 2 + 14
#define LOAD_FILE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * filesFound
#define LOAD_FILE_HEIGHT 35 + 14 * filesFound
#define LOAD_FILE_TITLE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * filesFound + 10
#define LOAD_FILE_OUTLINE_POSITION_X (SCREEN_WIDTH - 250) / 2
#define LOAD_FILE_OUTLINE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * filesFound + 26 + 14 * cursor
#define LOAD_FILE_OUTLINE_WIDTH 250
#define LOAD_FILE_OUTLINE_HEIGHT 14
#define LOAD_FILE_FILE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * filesFound + 30 + 14 * i
#define GAME_FINISHED_HEIGHT 50
#define GAME_FINISHED_TEXT_1_POSITION_Y SCREEN_HEIGHT / 2 + 14
#define GAME_FINISHED_TEXT_2_POSITION_Y SCREEN_HEIGHT / 2 + 28
#define SCORE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * SCORES_ON_PAGE
#define SCORE_HEIGHT 35 + 14 * SCORES_ON_PAGE
#define SCORE_TITLE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * SCORES_ON_PAGE + 10
#define SCORE_SCORE_POSITION_X windowManager->screen->w / 2 - 30
#define SCORE_SCORE_POSITION_Y SCREEN_HEIGHT / 2 - 10 * SCORES_ON_PAGE + 30 + 14 * i
#define CAR_SPAWN_TOP 0
#define CARS_HP 10
#define CAR_HEIGHT 90
#define FORCE_OUT_BORDER_LEFT_PLAYER 105
#define FORCE_OUT_BORDER_RIGHT_PLAYER SCREEN_WIDTH - 130
#define FORCE_OUT_BORDER_LEFT 125
#define FORCE_OUT_BORDER_RIGHT SCREEN_WIDTH - 150